midi_device: "Faderfox EC4"
midi_channel: 1

channels:
  - sample_dir: "/Users/dan/Sync/audio/collections/field/rubber/friction/"
  - sample_dir: "/Users/dan/Sync/audio/collections/field/wind/general/"
  - sample_dir: "/Users/dan/Sync/audio/collections/field/wood/misc/"
  - sample_dir: "/Users/dan/Sync/audio/collections/field/water/bubbles/"

midi:
  - param: volume
    channel: 0
    cc_id: 10
    initial_value: 64

  - param: filter_frequency
    channel: 0
    cc_id: 11
    initial_value: 32

  - param: filter_q
    channel: 0
    cc_id: 12
    initial_value: 0

  # - param: rate
  #   channel: 0
  #   cc_id: 13
  #   initial_value: 127

  - param: volume
    channel: 1
    cc_id: 20
    initial_value: 0

  - param: filter_frequency
    channel: 1
    cc_id: 21
    initial_value: 32

  - param: filter_q
    channel: 1
    cc_id: 22
    initial_value: 0

  # - param: rate
  #   channel: 1
  #   cc_id: 23
  #   initial_value: 127

  - param: volume
    channel: 2
    cc_id: 30
    initial_value: 0

  - param: filter_frequency
    channel: 2
    cc_id: 31
    initial_value: 32

  - param: filter_q
    channel: 2
    cc_id: 32
    initial_value: 0

  # - param: rate
  #   channel: 2
  #   cc_id: 33
  #   initial_value: 127

  - param: volume
    channel: 3
    cc_id: 40
    initial_value: 0

  - param: filter_frequency
    channel: 3
    cc_id: 41
    initial_value: 32

  - param: filter_q
    channel: 3
    cc_id: 42
    initial_value: 0

  # - param: rate
  #   channel: 3
  #   cc_id: 43
  #   initial_value: 127

